- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.3.0
  hooks:
    - id: prettier
      exclude: |
        (?x)(
            ^src\/dist\/assets\/index(.*)\.js|
            ^src\/dist\/assets\/index(.*)\.css
        )
